### ISSUE TITLE
Segmentation fault on Enter press

### ISSUE THREAD

**Issue by herrbischoff** [jonas/tig#480]
## Issue

I installed `tig` via Homebrew on Mac OS X. I saw the older issues regarding segmentation faults, those appear to have been resolved by an update of the formula. It all works great for me, except when pressing <kbd>Enter</kbd> in the main view. `tig` aborts with a segmentation fault every time:

```
88169 segmentation fault  tig
```

Here's the crash log:

```
Process:               tig [87768]
Path:                  /usr/local/Cellar/tig/2.1.1/bin/tig
Identifier:            tig
Version:               0
Code Type:             X86-64 (Native)
Parent Process:        zsh [83372]
Responsible:           iTerm2 [8190]
User ID:               502

Date/Time:             2016-02-23 10:12:31.115 +0100
OS Version:            Mac OS X 10.11.3 (15D21)
Report Version:        11
Anonymous UUID:        2D5FA402-BF02-990F-24C7-AFD3040466F7

Sleep/Wake UUID:       0849021E-8AEA-43E7-AED8-79183D3974E7

Time Awake Since Boot: 190000 seconds
Time Since Wake:       8900 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000723d052f0

VM Regions Near 0x723d052f0:
    VM_ALLOCATE            000000010d301000-000000010d302000 [    4K] rw-/rwx SM=ALI  
--> 
    MALLOC_TINY            00007fac23c00000-00007fac24000000 [ 4096K] rw-/rwx SM=COW  

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libncurses.5.4.dylib            0x00007fff850c2649 0x7fff8509f000 + 144969
1   libncurses.5.4.dylib            0x00007fff850c25b4 wresize + 1069
2   tig                             0x000000010cfef19a resize_display + 567
3   tig                             0x000000010cff1605 split_view + 58
4   tig                             0x000000010cff17f0 load_view + 318
5   tig                             0x000000010cffcaf7 main_request + 212
6   tig                             0x000000010cfe08ad main + 1567
7   libdyld.dylib                   0x00007fff853da5ad start + 1

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x00007fff74080408  rbx: 0x00007fac23c03ce0  rcx: 0x0000000000000002  rdx: 0x0000000000000000
  rdi: 0x00007fac23c03ce0  rsi: 0x0000000000000006  rbp: 0x00007fff52c20980  rsp: 0x00007fff52c20960
   r8: 0x0000000000000015   r9: 0x0000000000000000  r10: 0x0000000000000016  r11: 0x00007fac23c00000
  r12: 0x0000000723d052b0  r13: 0x0000000000000015  r14: 0x00007fac23c03ce0  r15: 0x00007fac23d14850
  rip: 0x00007fff850c2649  rfl: 0x0000000000010202  cr2: 0x0000000723d052f0

Logical CPU:     4
Error Code:      0x00000004
Trap Number:     14


Binary Images:
       0x10cfde000 -        0x10d009fff +tig (0) <1FCA7CC1-298C-3731-BE89-2E26CC4C687E> /usr/local/bin/tig
       0x10d029000 -        0x10d04aff7 +libreadline.6.dylib (0) <4830957C-B209-31B6-B99F-B2D80612F54A> /usr/local/opt/readline/lib/libreadline.6.dylib
       0x10d061000 -        0x10d09cfff +libncursesw.6.dylib (0) <849D502E-74D0-38C3-8949-BAAA1F88EC25> /usr/local/opt/ncurses/lib/libncursesw.6.dylib
    0x7fff6df1b000 -     0x7fff6df52007  dyld (360.19) <9D05FDF4-65CE-3B53-86D4-ABE1A5BF35F3> /usr/lib/dyld
    0x7fff83706000 -     0x7fff83724fff  libsystem_kernel.dylib (3248.30.4) <9CEB6C3B-1CAF-3C32-A9FD-93BC72CBCEA1> /usr/lib/system/libsystem_kernel.dylib
    0x7fff84c96000 -     0x7fff84ca1ff7  libcommonCrypto.dylib (60075.20.1) <766BC3F5-41F3-3315-BABC-72718A98EA92> /usr/lib/system/libcommonCrypto.dylib
    0x7fff84ca2000 -     0x7fff84cd1ffb  libsystem_m.dylib (3105) <26655445-CA97-321E-B221-801CB378D1AA> /usr/lib/system/libsystem_m.dylib
    0x7fff84f41000 -     0x7fff84f4aff3  libsystem_notify.dylib (150.20.3) <243FADE1-255A-3B78-8033-F336CD64B817> /usr/lib/system/libsystem_notify.dylib
    0x7fff8509f000 -     0x7fff850d0ff7  libncurses.5.4.dylib (46) <D4C10699-3E8F-3F42-A695-7490EA4B6B32> /usr/lib/libncurses.5.4.dylib
    0x7fff853d7000 -     0x7fff853daffb  libdyld.dylib (360.19) <AA629043-C6F6-32FE-8007-E3478E99ACA7> /usr/lib/system/libdyld.dylib
    0x7fff85426000 -     0x7fff854b3fff  libsystem_c.dylib (1082.20.4) <EAB38A6C-8671-3B13-B500-90EC1B912063> /usr/lib/system/libsystem_c.dylib
    0x7fff855ce000 -     0x7fff855dfff7  libsystem_trace.dylib (201.10.3) <B485369F-E3A1-319E-998C-89AAF606079E> /usr/lib/system/libsystem_trace.dylib
    0x7fff855e0000 -     0x7fff855e3ff7  libsystem_sandbox.dylib (460.30.1) <3E0036AF-FC64-3352-8DA4-6B550C2C2562> /usr/lib/system/libsystem_sandbox.dylib
    0x7fff87197000 -     0x7fff8719ffff  libsystem_networkextension.dylib (385.20.6) <DC8A102A-BF02-31A4-8914-65C34DF6B592> /usr/lib/system/libsystem_networkextension.dylib
    0x7fff87cb8000 -     0x7fff87cbdff7  libmacho.dylib (875.1) <CB745E1F-4885-3F96-B38B-2093DF488FD5> /usr/lib/system/libmacho.dylib
    0x7fff883d0000 -     0x7fff883f9fff  libc++abi.dylib (125) <DCCC8177-3D09-35BC-9784-2A04FEC4C71B> /usr/lib/libc++abi.dylib
    0x7fff89d7f000 -     0x7fff89d7fff7  libkeymgr.dylib (28) <09397E01-6066-3179-A50C-2CE666FDA929> /usr/lib/system/libkeymgr.dylib
    0x7fff8b0b0000 -     0x7fff8b0b1ffb  libremovefile.dylib (41) <B8D1A5FC-CFD5-3AAB-8A10-14DDC129710A> /usr/lib/system/libremovefile.dylib
    0x7fff8b93d000 -     0x7fff8b93efff  libsystem_blocks.dylib (65) <49D42329-7DE9-3413-92C3-A473A7E9CF35> /usr/lib/system/libsystem_blocks.dylib
    0x7fff8bb43000 -     0x7fff8bb44fff  libDiagnosticMessagesClient.dylib (100) <4243B6B4-21E9-355B-9C5A-95A216233B96> /usr/lib/libDiagnosticMessagesClient.dylib
    0x7fff8c22e000 -     0x7fff8c230ff7  libsystem_configuration.dylib (802.20.7) <5FD79070-36CC-3D02-BEA7-BB5D2AE97D5D> /usr/lib/system/libsystem_configuration.dylib
    0x7fff8c51f000 -     0x7fff8c527fe7  libsystem_platform.dylib (74.10.3) <D3A27E10-7F08-3603-ACC8-7A92B2C04BAB> /usr/lib/system/libsystem_platform.dylib
    0x7fff8ea77000 -     0x7fff8ea77ff7  libunc.dylib (29) <1D0F8265-F026-3CBD-93D3-F8DF14FFCE68> /usr/lib/system/libunc.dylib
    0x7fff8f477000 -     0x7fff8f4bdff7  libauto.dylib (186) <999E610F-41FC-32A3-ADCA-5EC049B65DFB> /usr/lib/libauto.dylib
    0x7fff8f933000 -     0x7fff8f960fff  libdispatch.dylib (501.20.1) <324C9189-2AF3-3356-847F-6F4CE1C6E901> /usr/lib/system/libdispatch.dylib
    0x7fff8ff4b000 -     0x7fff9003dff7  libiconv.2.dylib (44) <F05A0A5A-92A9-3668-8F20-F27CBDA26BE9> /usr/lib/libiconv.2.dylib
    0x7fff92edb000 -     0x7fff92ef2ff7  libsystem_asl.dylib (322.30.1) <9B500E4E-E462-321E-828E-5524DC984C1B> /usr/lib/system/libsystem_asl.dylib
    0x7fff94464000 -     0x7fff944c5ff7  libsystem_network.dylib (583.20.10) <865FE79A-A22D-3733-A14F-FC7B37F3AECD> /usr/lib/system/libsystem_network.dylib
    0x7fff9472c000 -     0x7fff94748ff7  libsystem_malloc.dylib (67) <9EECAB18-F025-34C4-8E32-7EFFA6720EFC> /usr/lib/system/libsystem_malloc.dylib
    0x7fff94749000 -     0x7fff9474dfff  libcache.dylib (75) <6B245C0A-F3EA-383B-A542-5B0D0456A41B> /usr/lib/system/libcache.dylib
    0x7fff94abd000 -     0x7fff94abffff  libsystem_coreservices.dylib (19.2) <1B3F5AFC-FFCD-3ECB-8B9A-5538366FB20D> /usr/lib/system/libsystem_coreservices.dylib
    0x7fff94c18000 -     0x7fff94c1fff7  libcompiler_rt.dylib (62) <D3C4AB40-23B4-3BC6-8C38-5B8758D14E80> /usr/lib/system/libcompiler_rt.dylib
    0x7fff950ca000 -     0x7fff950d2ffb  libsystem_dnssd.dylib (625.20.4) <945B5FB1-DA91-3D45-A961-A8FAD53C1E7E> /usr/lib/system/libsystem_dnssd.dylib
    0x7fff9520a000 -     0x7fff95220ff7  libsystem_coretls.dylib (83.20.8) <75C97D88-0A63-3093-AE83-DE33EB7405CE> /usr/lib/system/libsystem_coretls.dylib
    0x7fff95388000 -     0x7fff953fffe7  libcorecrypto.dylib (335.20.1) <C6BD205F-4ECE-37EE-BCAB-A76F39CDCFFA> /usr/lib/system/libcorecrypto.dylib
    0x7fff95ba3000 -     0x7fff95babfff  libcopyfile.dylib (127) <F5133269-0B22-388C-A57C-079667B6291E> /usr/lib/system/libcopyfile.dylib
    0x7fff966f8000 -     0x7fff966faff7  libquarantine.dylib (80) <163CF63A-7455-3D1F-AE57-8C4475A9204C> /usr/lib/system/libquarantine.dylib
    0x7fff96be8000 -     0x7fff96be8ff7  liblaunch.dylib (756.20.4) <EDF719D6-D2BB-38DD-8C94-4272BEFDA2CD> /usr/lib/system/liblaunch.dylib
    0x7fff980c1000 -     0x7fff980c6ff3  libunwind.dylib (35.3) <124E0F05-2350-3774-A32C-7F5BF38EDE73> /usr/lib/system/libunwind.dylib
    0x7fff9870f000 -     0x7fff98a71f3f  libobjc.A.dylib (680) <9F45830D-F1D5-3CDF-9461-1A5477ED7D1E> /usr/lib/libobjc.A.dylib
    0x7fff98bb9000 -     0x7fff98bbafff  libsystem_secinit.dylib (20) <FD6ECF2C-1489-32CA-981B-9045B5EB1FAA> /usr/lib/system/libsystem_secinit.dylib
    0x7fff98bd7000 -     0x7fff98c00fff  libsystem_info.dylib (477.20.1) <6513635B-4ADE-3B45-BF63-ED7AC565B0C9> /usr/lib/system/libsystem_info.dylib
    0x7fff98cbc000 -     0x7fff98d0fff7  libc++.1.dylib (120.1) <8FC3D139-8055-3498-9AC5-6467CB7F4D14> /usr/lib/libc++.1.dylib
    0x7fff98ee9000 -     0x7fff98eeaffb  libSystem.B.dylib (1226.10.1) <5A4257EF-3145-3BB3-87A4-0D2404A9462D> /usr/lib/libSystem.B.dylib
    0x7fff99b85000 -     0x7fff99baefff  libxpc.dylib (756.20.4) <61AB4610-9304-354C-9E9B-D57198AE9866> /usr/lib/system/libxpc.dylib
    0x7fff99baf000 -     0x7fff99bb8ff7  libsystem_pthread.dylib (138.10.4) <327CECD0-B881-3153-8FCC-4FD4818B7F16> /usr/lib/system/libsystem_pthread.dylib

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 1
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 32094560
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=100.3M resident=0K(0%) swapped_out_or_unallocated=100.3M(100%)
Writable regions: Total=49.5M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=49.5M(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Activity Tracing                  2048K        2 
Kernel Alloc Once                    4K        2 
MALLOC                            39.3M       11 
MALLOC guard page                   16K        4 
STACK GUARD                       56.0M        2 
Stack                             8192K        2 
VM_ALLOCATE                          4K        2 
__DATA                            1596K       47 
__LINKEDIT                        91.2M        6 
__TEXT                            9348K       47 
shared memory                       12K        4 
===========                     =======  ======= 
TOTAL                            207.2M      118 
```
## Environment

``` bash
$ tig -v
tig version 2.1.1
```

``` bash
$ brew -v
Homebrew 0.9.5 (git revision cd27e; last commit 2016-02-22)
```

``` bash
$ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.11.3
BuildVersion:   15D21
```

**Comment by herrbischoff** [comment]
Bump.

**Comment by jonas** [comment]
I'll take a look tonight. Cannot reproduce on my work box.

**Comment by h3xx** [comment]
Looks like libncurses is throwing the seggie in its `wresize` function.

What specific version of ncurses do you have installed?

**Comment by herrbischoff** [comment]
@jonas: Thanks!

@h3xx: That's ncurses 6.0, installed via Homebrew on (in the meantime updated to) Mac OS X 10.11.4. Here's the HB formula for the installation: https://github.com/Homebrew/homebrew-dupes/blob/master/ncurses.rb

I installed by letting HB compile the sources instead if installing a bottle.

**Comment by herrbischoff** [comment]
Just tried it again and now I get another error:

```
'tig' terminated by signal SIGSEGV (Address boundary error)
```

Crashlog:

```
Process:               tig [74337]
Path:                  /usr/local/Cellar/tig/2.1.1/bin/tig
Identifier:            tig
Version:               0
Code Type:             X86-64 (Native)
Parent Process:        fish [72661]
Responsible:           tig [74337]
User ID:               502

Date/Time:             2016-03-30 18:38:21.192 +0200
OS Version:            Mac OS X 10.11.4 (15E65)
Report Version:        11
Anonymous UUID:        2D5FA402-BF02-990F-24C7-AFD3040466F7

Sleep/Wake UUID:       A626EE47-72C5-4EED-85B8-FC00906DA9E5

Time Awake Since Boot: 120000 seconds
Time Since Wake:       2600 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x00007fd49c7ffff8
Exception Note:        EXC_CORPSE_NOTIFY

VM Regions Near 0x7fd49c7ffff8:
    MALLOC_TINY            00007fd49c000000-00007fd49c200000 [ 2048K] rw-/rwx SM=COW  
--> 
    MALLOC_SMALL           00007fd49c800000-00007fd49d000000 [ 8192K] rw-/rwx SM=PRV  

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   tig                           	0x0000000109d6be7a file_finder_draw + 28
1   tig                           	0x0000000109d6c0f1 file_finder_input_handler + 256
2   tig                           	0x0000000109d5ab27 prompt_input + 390
3   tig                           	0x0000000109d6bc46 open_file_finder + 656
4   tig                           	0x0000000109d65e0f open_blob_view + 96
5   tig                           	0x0000000109d4eb0c main + 2174
6   libdyld.dylib                 	0x00007fff8d4d25ad start + 1

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0xffffffffffffffff  rbx: 0x00007fd49a705b50  rcx: 0x000000000000001e  rdx: 0x000000000000003d
  rdi: 0x00007fff55eb2980  rsi: 0xffffffffffffffe1  rbp: 0x00007fff55eb24b0  rsp: 0x00007fff55eb2480
   r8: 0x0000000000000000   r9: 0x00000000ffff8000  r10: 0xffffffffffffffff  r11: 0xffffffd544853bc0
  r12: 0x00007fff55eb2530  r13: 0x0000000000000000  r14: 0x00007fd49c800000  r15: 0x00007fff55eb2980
  rip: 0x0000000109d6be7a  rfl: 0x0000000000010297  cr2: 0x00007fd49c7ffff8
  
Logical CPU:     0
Error Code:      0x00000004
Trap Number:     14


Binary Images:
       0x109d4c000 -        0x109d77fff +tig (0) <1FCA7CC1-298C-3731-BE89-2E26CC4C687E> /usr/local/bin/tig
       0x109d9a000 -        0x109dbbff7 +libreadline.6.dylib (0) <4830957C-B209-31B6-B99F-B2D80612F54A> /usr/local/opt/readline/lib/libreadline.6.dylib
       0x109dd5000 -        0x109e10fff +libncursesw.6.dylib (0) <849D502E-74D0-38C3-8949-BAAA1F88EC25> /usr/local/opt/ncurses/lib/libncursesw.6.dylib
    0x7fff5fe45000 -     0x7fff5fe7c0d7  dyld (360.21) <D9B236BC-4AC1-325F-B3EF-3F06DBDA7119> /usr/lib/dyld
    0x7fff80eed000 -     0x7fff80f1eff7  libncurses.5.4.dylib (46) <D4C10699-3E8F-3F42-A695-7490EA4B6B32> /usr/lib/libncurses.5.4.dylib
    0x7fff80ffa000 -     0x7fff81040ff7  libauto.dylib (186) <999E610F-41FC-32A3-ADCA-5EC049B65DFB> /usr/lib/libauto.dylib
    0x7fff82bd0000 -     0x7fff82bd4fff  libcache.dylib (75) <9548AAE9-2AB7-3525-9ECE-A2A7C4688447> /usr/lib/system/libcache.dylib
    0x7fff850c7000 -     0x7fff850ceff7  libcompiler_rt.dylib (62) <A13ECF69-F59F-38AE-8609-7B731450FBCD> /usr/lib/system/libcompiler_rt.dylib
    0x7fff86b24000 -     0x7fff86b51fff  libdispatch.dylib (501.40.12) <C7499857-61A5-3D7D-A5EA-65DCC8C3DF92> /usr/lib/system/libdispatch.dylib
    0x7fff8711a000 -     0x7fff8711fff3  libunwind.dylib (35.3) <F6EB48E5-4D12-359A-AB54-C937FBBE9043> /usr/lib/system/libunwind.dylib
    0x7fff872b5000 -     0x7fff8731bff7  libsystem_network.dylib (583.40.20) <269E5ADD-6922-31E2-8D55-7B777263AC0D> /usr/lib/system/libsystem_network.dylib
    0x7fff873ba000 -     0x7fff873d1ff7  libsystem_asl.dylib (323.40.3) <007F9094-317A-33EA-AF62-BAEAAB48C0F7> /usr/lib/system/libsystem_asl.dylib
    0x7fff874a6000 -     0x7fff874afff7  libsystem_pthread.dylib (138.10.4) <3DD1EF4C-1D1B-3ABF-8CC6-B3B1CEEE9559> /usr/lib/system/libsystem_pthread.dylib
    0x7fff88f82000 -     0x7fff88fabfff  libc++abi.dylib (125) <DCCC8177-3D09-35BC-9784-2A04FEC4C71B> /usr/lib/libc++abi.dylib
    0x7fff88fac000 -     0x7fff88fcaff7  libsystem_kernel.dylib (3248.40.184) <88C17B7F-1CD8-3979-A1A9-F7BDB4FCE789> /usr/lib/system/libsystem_kernel.dylib
    0x7fff89035000 -     0x7fff89037ff7  libquarantine.dylib (80) <0F4169F0-0C84-3A25-B3AE-E47B3586D908> /usr/lib/system/libquarantine.dylib
    0x7fff89051000 -     0x7fff89051ff7  libunc.dylib (29) <DDB1E947-C775-33B8-B461-63E5EB698F0E> /usr/lib/system/libunc.dylib
    0x7fff8932d000 -     0x7fff89335fff  libcopyfile.dylib (127) <A48637BC-F3F2-34F2-BB68-4C65FD012832> /usr/lib/system/libcopyfile.dylib
    0x7fff893b6000 -     0x7fff893bfff3  libsystem_notify.dylib (150.40.1) <D48BDE34-0F7E-34CA-A0FF-C578E39987CC> /usr/lib/system/libsystem_notify.dylib
    0x7fff89479000 -     0x7fff89479ff7  liblaunch.dylib (765.40.36) <1CD7619D-AF2E-34D1-8EC6-8021CF473D9B> /usr/lib/system/liblaunch.dylib
    0x7fff89487000 -     0x7fff89492ff7  libcommonCrypto.dylib (60075.40.2) <B9D08EB8-FB35-3F7B-8A1C-6FCE3F07B7E7> /usr/lib/system/libcommonCrypto.dylib
    0x7fff895d6000 -     0x7fff895d7ffb  libSystem.B.dylib (1226.10.1) <CD307E99-FC5C-3575-BCCE-0C861AA63124> /usr/lib/libSystem.B.dylib
    0x7fff89636000 -     0x7fff89637fff  libDiagnosticMessagesClient.dylib (100) <4243B6B4-21E9-355B-9C5A-95A216233B96> /usr/lib/libDiagnosticMessagesClient.dylib
    0x7fff896ce000 -     0x7fff896eaff7  libsystem_malloc.dylib (67.40.1) <5748E8B2-F81C-34C6-8B13-456213127678> /usr/lib/system/libsystem_malloc.dylib
    0x7fff896eb000 -     0x7fff896f3ffb  libsystem_dnssd.dylib (625.40.20) <86A05653-DCA0-3345-B29F-F320029AA05E> /usr/lib/system/libsystem_dnssd.dylib
    0x7fff897f3000 -     0x7fff897f4fff  libsystem_secinit.dylib (20) <32B1A8C6-DC84-3F4F-B8CE-9A52B47C3E6B> /usr/lib/system/libsystem_secinit.dylib
    0x7fff8cdfd000 -     0x7fff8ce05fef  libsystem_platform.dylib (74.40.2) <29A905EF-6777-3C33-82B0-6C3A88C4BA15> /usr/lib/system/libsystem_platform.dylib
    0x7fff8d4a5000 -     0x7fff8d4cefff  libsystem_info.dylib (477.40.5) <6B01C09E-A3E5-3C71-B370-D0CABD11A436> /usr/lib/system/libsystem_info.dylib
    0x7fff8d4cf000 -     0x7fff8d4d2ffb  libdyld.dylib (360.21) <8390E026-F7DE-3C32-9486-3DFF6BD131B0> /usr/lib/system/libdyld.dylib
    0x7fff8db79000 -     0x7fff8db90ff7  libsystem_coretls.dylib (83.40.5) <C90DAE38-4082-381C-A185-2A6A8B677628> /usr/lib/system/libsystem_coretls.dylib
    0x7fff8de0c000 -     0x7fff8de35ff7  libxpc.dylib (765.40.36) <2CC7CF36-66D4-301B-A6D8-EBAE7405B008> /usr/lib/system/libxpc.dylib
    0x7fff8e4e1000 -     0x7fff8e558feb  libcorecrypto.dylib (335.40.8) <9D300121-CAF8-3894-8774-DF38FA65F238> /usr/lib/system/libcorecrypto.dylib
    0x7fff8ec44000 -     0x7fff8ec44ff7  libkeymgr.dylib (28) <8371CE54-5FDD-3CE9-B3DF-E98C761B6FE0> /usr/lib/system/libkeymgr.dylib
    0x7fff8f73b000 -     0x7fff8f7c8fff  libsystem_c.dylib (1082.20.4) <CDEBF2BB-A578-30F5-846F-96274951C3C5> /usr/lib/system/libsystem_c.dylib
    0x7fff903f3000 -     0x7fff903f5fff  libsystem_coreservices.dylib (19.2) <1B3F5AFC-FFCD-3ECB-8B9A-5538366FB20D> /usr/lib/system/libsystem_coreservices.dylib
    0x7fff90f57000 -     0x7fff90faaff7  libc++.1.dylib (120.1) <8FC3D139-8055-3498-9AC5-6467CB7F4D14> /usr/lib/libc++.1.dylib
    0x7fff90fab000 -     0x7fff90fdaffb  libsystem_m.dylib (3105) <08E1A4B2-6448-3DFE-A58C-ACC7335BE7E4> /usr/lib/system/libsystem_m.dylib
    0x7fff91559000 -     0x7fff9155cfff  libsystem_sandbox.dylib (460.40.33) <30671DCC-265F-325A-B33D-11CD336B3DA3> /usr/lib/system/libsystem_sandbox.dylib
    0x7fff92880000 -     0x7fff92881fff  libsystem_blocks.dylib (65) <1244D9D5-F6AA-35BB-B307-86851C24B8E5> /usr/lib/system/libsystem_blocks.dylib
    0x7fff936e3000 -     0x7fff936e8ff7  libmacho.dylib (875.1) <318264FA-58F1-39D8-8285-1F6254EE410E> /usr/lib/system/libmacho.dylib
    0x7fff94105000 -     0x7fff9410dfff  libsystem_networkextension.dylib (385.40.36) <66095DC7-6539-38F2-95EE-458F15F6D014> /usr/lib/system/libsystem_networkextension.dylib
    0x7fff946b7000 -     0x7fff94a19f3f  libobjc.A.dylib (680) <7489D2D6-1EFD-3414-B18D-2AECCCC90286> /usr/lib/libobjc.A.dylib
    0x7fff94b7c000 -     0x7fff94c6eff7  libiconv.2.dylib (44) <F05A0A5A-92A9-3668-8F20-F27CBDA26BE9> /usr/lib/libiconv.2.dylib
    0x7fff94ce4000 -     0x7fff94ce6ff7  libsystem_configuration.dylib (802.40.13) <3DEB7DF9-6804-37E1-BC83-0166882FF0FF> /usr/lib/system/libsystem_configuration.dylib
    0x7fff95006000 -     0x7fff95017ff7  libsystem_trace.dylib (201.10.3) <25104542-5251-3E8D-B14A-9E37207218BC> /usr/lib/system/libsystem_trace.dylib
    0x7fff956b3000 -     0x7fff956b4ffb  libremovefile.dylib (41) <552EF39E-14D7-363E-9059-4565AC2F894E> /usr/lib/system/libremovefile.dylib

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 7
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 18261671
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=100.7M resident=0K(0%) swapped_out_or_unallocated=100.7M(100%)
Writable regions: Total=50.6M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=50.6M(100%)
 
                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Activity Tracing                  2048K        2 
Kernel Alloc Once                    4K        2 
MALLOC                            38.3M       15 
MALLOC guard page                   16K        4 
Process Corpse Info               2048K        2 
STACK GUARD                       56.0M        2 
Stack                             8192K        2 
VM_ALLOCATE                          4K        2 
__DATA                            1592K       48 
__LINKEDIT                        91.6M        6 
__TEXT                            9372K       47 
shared memory                       12K        4 
===========                     =======  ======= 
TOTAL                            208.6M      124 
```

**Comment by herrbischoff** [comment]
> I'll take a look tonight. Cannot reproduce on my work box.

@jonas: Did you have a chance yet to take a look? Let me know when I can do something on my end to pinpoint the issue better.

**Comment by jonas** [comment]
The latest crash you listed has been fixed in 718c6e94fcc111e5607d6ca0bf3d15271adc0d97 which has not been released yet. Can you try and install `HEAD`?

**Comment by herrbischoff** [comment]
Reinstalled `HEAD`:

```
$ tig -v
tig version 2.1.1-g3a5eb60-dirty
```

Yields the following crash upon pushing Enter:

```
'tig' terminated by signal SIGSEGV (Address boundary error)
```

Crash log:

```
Process:               tig [59944]
Path:                  /usr/local/Cellar/tig/HEAD/bin/tig
Identifier:            tig
Version:               0
Code Type:             X86-64 (Native)
Parent Process:        fish [16509]
Responsible:           tig [59944]
User ID:               502

Date/Time:             2016-03-31 21:46:13.320 +0200
OS Version:            Mac OS X 10.11.4 (15E65)
Report Version:        11
Anonymous UUID:        2D5FA402-BF02-990F-24C7-AFD3040466F7

Sleep/Wake UUID:       9F3788E3-2F00-4FEF-AB26-C4C0FE698F6C

Time Awake Since Boot: 190000 seconds
Time Since Wake:       9300 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000739d00f90
Exception Note:        EXC_CORPSE_NOTIFY

VM Regions Near 0x739d00f90:
    VM_ALLOCATE            000000010ac5c000-000000010ac5d000 [    4K] rw-/rwx SM=ALI  
--> 
    MALLOC_TINY            00007fed39c00000-00007fed39e00000 [ 2048K] rw-/rwx SM=COW  

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libncurses.5.4.dylib          	0x00007fff80f10649 0x7fff80eed000 + 144969
1   libncurses.5.4.dylib          	0x00007fff80f105b4 wresize + 1069
2   tig                           	0x000000010a7499be resize_display + 641
3   tig                           	0x000000010a74bab2 split_view + 58
4   tig                           	0x000000010a74bc43 load_view + 292
5   tig                           	0x000000010a757ab1 main_request + 233
6   tig                           	0x000000010a73ac90 main + 1647
7   libdyld.dylib                 	0x00007fff8d4d25ad start + 1

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x00007fff70c66408  rbx: 0x00007fed39e00000  rcx: 0x0000000000000003  rdx: 0x0000000000000039
  rdi: 0x00007fed39e00000  rsi: 0x000000000000003b  rbp: 0x00007fff554c6940  rsp: 0x00007fff554c6920
   r8: 0x000000000000003b   r9: 0x0000000000000000  r10: 0x000000000000003c  r11: 0x00007fed39e00000
  r12: 0x0000000739d00f50  r13: 0x000000000000003c  r14: 0x00007fed39e00000  r15: 0x00007fed39d041b0
  rip: 0x00007fff80f10649  rfl: 0x0000000000010206  cr2: 0x0000000739d00f90
  
Logical CPU:     0
Error Code:      0x00000004
Trap Number:     14


Binary Images:
       0x10a738000 -        0x10a764ffb +tig (0) <642A1BEC-95AF-3AC2-9766-E7E2EC38C35A> /usr/local/bin/tig
       0x10a787000 -        0x10a7a8ff7 +libreadline.6.dylib (0) <4830957C-B209-31B6-B99F-B2D80612F54A> /usr/local/opt/readline/lib/libreadline.6.dylib
       0x10a7c2000 -        0x10a7fdfff +libncursesw.6.dylib (0) <849D502E-74D0-38C3-8949-BAAA1F88EC25> /usr/local/opt/ncurses/lib/libncursesw.6.dylib
    0x7fff6205c000 -     0x7fff620930d7  dyld (360.21) <D9B236BC-4AC1-325F-B3EF-3F06DBDA7119> /usr/lib/dyld
    0x7fff80eed000 -     0x7fff80f1eff7  libncurses.5.4.dylib (46) <D4C10699-3E8F-3F42-A695-7490EA4B6B32> /usr/lib/libncurses.5.4.dylib
    0x7fff80ffa000 -     0x7fff81040ff7  libauto.dylib (186) <999E610F-41FC-32A3-ADCA-5EC049B65DFB> /usr/lib/libauto.dylib
    0x7fff82bd0000 -     0x7fff82bd4fff  libcache.dylib (75) <9548AAE9-2AB7-3525-9ECE-A2A7C4688447> /usr/lib/system/libcache.dylib
    0x7fff850c7000 -     0x7fff850ceff7  libcompiler_rt.dylib (62) <A13ECF69-F59F-38AE-8609-7B731450FBCD> /usr/lib/system/libcompiler_rt.dylib
    0x7fff86b24000 -     0x7fff86b51fff  libdispatch.dylib (501.40.12) <C7499857-61A5-3D7D-A5EA-65DCC8C3DF92> /usr/lib/system/libdispatch.dylib
    0x7fff8711a000 -     0x7fff8711fff3  libunwind.dylib (35.3) <F6EB48E5-4D12-359A-AB54-C937FBBE9043> /usr/lib/system/libunwind.dylib
    0x7fff872b5000 -     0x7fff8731bff7  libsystem_network.dylib (583.40.20) <269E5ADD-6922-31E2-8D55-7B777263AC0D> /usr/lib/system/libsystem_network.dylib
    0x7fff873ba000 -     0x7fff873d1ff7  libsystem_asl.dylib (323.40.3) <007F9094-317A-33EA-AF62-BAEAAB48C0F7> /usr/lib/system/libsystem_asl.dylib
    0x7fff874a6000 -     0x7fff874afff7  libsystem_pthread.dylib (138.10.4) <3DD1EF4C-1D1B-3ABF-8CC6-B3B1CEEE9559> /usr/lib/system/libsystem_pthread.dylib
    0x7fff88f82000 -     0x7fff88fabfff  libc++abi.dylib (125) <DCCC8177-3D09-35BC-9784-2A04FEC4C71B> /usr/lib/libc++abi.dylib
    0x7fff88fac000 -     0x7fff88fcaff7  libsystem_kernel.dylib (3248.40.184) <88C17B7F-1CD8-3979-A1A9-F7BDB4FCE789> /usr/lib/system/libsystem_kernel.dylib
    0x7fff89035000 -     0x7fff89037ff7  libquarantine.dylib (80) <0F4169F0-0C84-3A25-B3AE-E47B3586D908> /usr/lib/system/libquarantine.dylib
    0x7fff89051000 -     0x7fff89051ff7  libunc.dylib (29) <DDB1E947-C775-33B8-B461-63E5EB698F0E> /usr/lib/system/libunc.dylib
    0x7fff8932d000 -     0x7fff89335fff  libcopyfile.dylib (127) <A48637BC-F3F2-34F2-BB68-4C65FD012832> /usr/lib/system/libcopyfile.dylib
    0x7fff893b6000 -     0x7fff893bfff3  libsystem_notify.dylib (150.40.1) <D48BDE34-0F7E-34CA-A0FF-C578E39987CC> /usr/lib/system/libsystem_notify.dylib
    0x7fff89479000 -     0x7fff89479ff7  liblaunch.dylib (765.40.36) <1CD7619D-AF2E-34D1-8EC6-8021CF473D9B> /usr/lib/system/liblaunch.dylib
    0x7fff89487000 -     0x7fff89492ff7  libcommonCrypto.dylib (60075.40.2) <B9D08EB8-FB35-3F7B-8A1C-6FCE3F07B7E7> /usr/lib/system/libcommonCrypto.dylib
    0x7fff895d6000 -     0x7fff895d7ffb  libSystem.B.dylib (1226.10.1) <CD307E99-FC5C-3575-BCCE-0C861AA63124> /usr/lib/libSystem.B.dylib
    0x7fff89636000 -     0x7fff89637fff  libDiagnosticMessagesClient.dylib (100) <4243B6B4-21E9-355B-9C5A-95A216233B96> /usr/lib/libDiagnosticMessagesClient.dylib
    0x7fff896ce000 -     0x7fff896eaff7  libsystem_malloc.dylib (67.40.1) <5748E8B2-F81C-34C6-8B13-456213127678> /usr/lib/system/libsystem_malloc.dylib
    0x7fff896eb000 -     0x7fff896f3ffb  libsystem_dnssd.dylib (625.40.20) <86A05653-DCA0-3345-B29F-F320029AA05E> /usr/lib/system/libsystem_dnssd.dylib
    0x7fff897f3000 -     0x7fff897f4fff  libsystem_secinit.dylib (20) <32B1A8C6-DC84-3F4F-B8CE-9A52B47C3E6B> /usr/lib/system/libsystem_secinit.dylib
    0x7fff8cdfd000 -     0x7fff8ce05fef  libsystem_platform.dylib (74.40.2) <29A905EF-6777-3C33-82B0-6C3A88C4BA15> /usr/lib/system/libsystem_platform.dylib
    0x7fff8d4a5000 -     0x7fff8d4cefff  libsystem_info.dylib (477.40.5) <6B01C09E-A3E5-3C71-B370-D0CABD11A436> /usr/lib/system/libsystem_info.dylib
    0x7fff8d4cf000 -     0x7fff8d4d2ffb  libdyld.dylib (360.21) <8390E026-F7DE-3C32-9486-3DFF6BD131B0> /usr/lib/system/libdyld.dylib
    0x7fff8db79000 -     0x7fff8db90ff7  libsystem_coretls.dylib (83.40.5) <C90DAE38-4082-381C-A185-2A6A8B677628> /usr/lib/system/libsystem_coretls.dylib
    0x7fff8de0c000 -     0x7fff8de35ff7  libxpc.dylib (765.40.36) <2CC7CF36-66D4-301B-A6D8-EBAE7405B008> /usr/lib/system/libxpc.dylib
    0x7fff8e4e1000 -     0x7fff8e558feb  libcorecrypto.dylib (335.40.8) <9D300121-CAF8-3894-8774-DF38FA65F238> /usr/lib/system/libcorecrypto.dylib
    0x7fff8ec44000 -     0x7fff8ec44ff7  libkeymgr.dylib (28) <8371CE54-5FDD-3CE9-B3DF-E98C761B6FE0> /usr/lib/system/libkeymgr.dylib
    0x7fff8f73b000 -     0x7fff8f7c8fff  libsystem_c.dylib (1082.20.4) <CDEBF2BB-A578-30F5-846F-96274951C3C5> /usr/lib/system/libsystem_c.dylib
    0x7fff903f3000 -     0x7fff903f5fff  libsystem_coreservices.dylib (19.2) <1B3F5AFC-FFCD-3ECB-8B9A-5538366FB20D> /usr/lib/system/libsystem_coreservices.dylib
    0x7fff90f57000 -     0x7fff90faaff7  libc++.1.dylib (120.1) <8FC3D139-8055-3498-9AC5-6467CB7F4D14> /usr/lib/libc++.1.dylib
    0x7fff90fab000 -     0x7fff90fdaffb  libsystem_m.dylib (3105) <08E1A4B2-6448-3DFE-A58C-ACC7335BE7E4> /usr/lib/system/libsystem_m.dylib
    0x7fff91559000 -     0x7fff9155cfff  libsystem_sandbox.dylib (460.40.33) <30671DCC-265F-325A-B33D-11CD336B3DA3> /usr/lib/system/libsystem_sandbox.dylib
    0x7fff92880000 -     0x7fff92881fff  libsystem_blocks.dylib (65) <1244D9D5-F6AA-35BB-B307-86851C24B8E5> /usr/lib/system/libsystem_blocks.dylib
    0x7fff936e3000 -     0x7fff936e8ff7  libmacho.dylib (875.1) <318264FA-58F1-39D8-8285-1F6254EE410E> /usr/lib/system/libmacho.dylib
    0x7fff94105000 -     0x7fff9410dfff  libsystem_networkextension.dylib (385.40.36) <66095DC7-6539-38F2-95EE-458F15F6D014> /usr/lib/system/libsystem_networkextension.dylib
    0x7fff946b7000 -     0x7fff94a19f3f  libobjc.A.dylib (680) <7489D2D6-1EFD-3414-B18D-2AECCCC90286> /usr/lib/libobjc.A.dylib
    0x7fff94b7c000 -     0x7fff94c6eff7  libiconv.2.dylib (44) <F05A0A5A-92A9-3668-8F20-F27CBDA26BE9> /usr/lib/libiconv.2.dylib
    0x7fff94ce4000 -     0x7fff94ce6ff7  libsystem_configuration.dylib (802.40.13) <3DEB7DF9-6804-37E1-BC83-0166882FF0FF> /usr/lib/system/libsystem_configuration.dylib
    0x7fff95006000 -     0x7fff95017ff7  libsystem_trace.dylib (201.10.3) <25104542-5251-3E8D-B14A-9E37207218BC> /usr/lib/system/libsystem_trace.dylib
    0x7fff956b3000 -     0x7fff956b4ffb  libremovefile.dylib (41) <552EF39E-14D7-363E-9059-4565AC2F894E> /usr/lib/system/libremovefile.dylib

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 3
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 26023657
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=100.7M resident=0K(0%) swapped_out_or_unallocated=100.7M(100%)
Writable regions: Total=49.5M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=49.5M(100%)
 
                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Activity Tracing                  2048K        2 
Kernel Alloc Once                    4K        2 
MALLOC                            37.3M       15 
MALLOC guard page                   16K        4 
Process Corpse Info               2048K        2 
STACK GUARD                       56.0M        2 
Stack                             8192K        2 
VM_ALLOCATE                          4K        2 
__DATA                            1592K       47 
__LINKEDIT                        91.6M        6 
__TEXT                            9376K       47 
shared memory                       12K        4 
===========                     =======  ======= 
TOTAL                            207.6M      123 
```

**Comment by jonas** [comment]
OK, tried to update brew and ncurses to 6.0.1 and was not able to reproduce. Next step is to update OSX and see if that triggers it.

If I am not able to reproduce the next step would likely be to get more information by running tig in a debugger:

    $ git clone https://github.com/jonas/tig.git /tmp
    $ cd /tmp
    $ make all-debug
    $ lldb ./src/tig
    (lldb) run

**Comment by herrbischoff** [comment]
I did what you suggested, which triggers compile errors. (As you'll probably guess, `❯` is my prompt)

```
~/tmp
❯ git clone https://github.com/jonas/tig.git
Cloning into 'tig'...
remote: Counting objects: 11024, done.
remote: Total 11024 (delta 0), reused 0 (delta 0), pack-reused 11023
Receiving objects: 100% (11024/11024), 4.95 MiB | 114.00 KiB/s, done.
Resolving deltas: 100% (7529/7529), done.
Checking connectivity... done.

~/tmp
❯ cd tig/

~/tmp/tig master
❯ make all-debug
        CC  src/tig.o
        CC  src/types.o
        CC  src/string.o
        CC  src/util.o
        CC  src/map.o
        CC  src/argv.o
        CC  src/io.o
        CC  src/refdb.o
       GEN  src/builtin-config.c
        CC  src/builtin-config.o
        CC  src/request.o
        CC  src/line.o
        CC  src/keys.o
        CC  src/repo.o
        CC  src/options.o
        CC  src/draw.o
        CC  src/prompt.o
        CC  src/display.o
        CC  src/view.o
        CC  src/search.o
        CC  src/parse.o
        CC  src/watch.o
        CC  src/pager.o
        CC  src/log.o
        CC  src/diff.o
        CC  src/help.o
        CC  src/tree.o
        CC  src/blob.o
        CC  src/blame.o
        CC  src/refs.o
        CC  src/status.o
        CC  src/stage.o
        CC  src/main.o
        CC  src/stash.o
        CC  src/grep.o
        CC  src/ui.o
        CC  src/graph.o
        CC  src/graph-v1.o
        CC  src/graph-v2.o
src/graph-v2.c:628:6: error: logical not is only applied to the left hand side of this comparison [-Werror,-Wlogical-not-parentheses]
        if (!pos == graph->prev_position)
            ^    ~~
src/graph-v2.c:628:6: note: add parentheses after the '!' to evaluate the comparison first
        if (!pos == graph->prev_position)
            ^
             (                          )
src/graph-v2.c:628:6: note: add parentheses around left hand side expression to silence this warning
        if (!pos == graph->prev_position)
            ^
            (   )
src/graph-v2.c:631:6: error: logical not is only applied to the left hand side of this comparison [-Werror,-Wlogical-not-parentheses]
        if (!strcmp(graph->row.columns[pos].id, graph->prev_row.columns[pos].id) == 0)
            ^                                                                    ~~
src/graph-v2.c:631:6: note: add parentheses after the '!' to evaluate the comparison first
        if (!strcmp(graph->row.columns[pos].id, graph->prev_row.columns[pos].id) == 0)
            ^
             (                                                                       )
src/graph-v2.c:631:6: note: add parentheses around left hand side expression to silence this warning
        if (!strcmp(graph->row.columns[pos].id, graph->prev_row.columns[pos].id) == 0)
            ^
            (                                                                   )
2 errors generated.
make: *** [src/graph-v2.o] Error 1
```

## Environment

```
❯ cc --version
Apple LLVM version 7.3.0 (clang-703.0.29)
Target: x86_64-apple-darwin15.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by jonas** [comment]
I've pushed a fix for the compilation error in cf74a8ce3854e09e66a9df3680ee1e350ace91c6 after having updated my local XCode.

Looking closer at the crash report one thing stands out namely that the ncurses version in the stack trace is not the same as the one listed in the binary:

```
Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libncurses.5.4.dylib            0x00007fff80f10649 0x7fff80eed000 + 144969
1   libncurses.5.4.dylib            0x00007fff80f105b4 wresize + 1069
2   tig                             0x000000010a7499be resize_display + 641

Binary Images:
       0x10a738000 -        0x10a764ffb +tig (0) <642A1BEC-95AF-3AC2-9766-E7E2EC38C35A> /usr/local/bin/tig
       0x10a787000 -        0x10a7a8ff7 +libreadline.6.dylib (0) <4830957C-B209-31B6-B99F-B2D80612F54A> /usr/local/opt/readline/lib/libreadline.6.dylib
       0x10a7c2000 -        0x10a7fdfff +libncursesw.6.dylib (0) <849D502E-74D0-38C3-8949-BAAA1F88EC25> /usr/local/opt/ncurses/lib/libncursesw.6.dylib
```

**Comment by herrbischoff** [comment]
After your change `tig` now builds smoothly when I do it manually. There is also no error, no segfault. It works perfectly. The HEAD version via Homebrew still crashes.

Accounting for your crash report excerpt, the only explanation I can come up with is that ncurses is shipped with OS X by default but Homebrew offers a newer one through dupes. This is done so that if a formula requires a newer version than the one included in the system, it can build when explicitly told where to look. It appears that the Homebrew build mixes both ncurses somehow.

If I remove ncurses via `brew remove ncurses` and try to start up `tig`, I get the following (expected) error (I use fish as my shell):

```
dyld: Library not loaded: /usr/local/opt/ncurses/lib/libncursesw.6.dylib
  Referenced from: /usr/local/bin/tig
  Reason: image not found
fish: 'tig' terminated by signal SIGTRAP (Trace or breakpoint trap)
```

Interestingly enough, after a `brew reinstall --HEAD tig`, the Homebrew version works identically. So the culprit is the dupe ncurses 6 formula that mixes itself into the build process.
