### ISSUE TITLE
line-graphics don't behave too nice

### ISSUE THREAD

**Issue by Vampire** [jonas/tig#527]
- When starting `tig` in ISO-8859-1 with `LANG=en_US.ISO-8859-1 tig`, the `default` and `ascii` `line-graphics` look good, but switching to `utf-8` looks very ugly like
  
  ```
  â~W~Oâ~T~@â~U® Merge branch 'foo'
  â~W~O | f
  | â~W~O e
  â~W~O | d
  â~W~O | c
  | â~W~O b
  â~W~Nâ~T~@â~U¯ a
  ```
  
  Maybe it would be possible to prevent using `utf-8` if locale is not `utf-8`?
- When switching `line-graphics` in split view (having pressed return key on a commit in main view), the vertical ruler is not repainted until you select another line or un-split and resplit the view, no matter from or to which setting you switch
- When starting tig in UTF-8 with `LANG=en_US.UTF-8 tig`, the `ascii` `line-graphics` look good, but switching to `utf-8` or `default` looks very ugly.
  - Having `utf-8`, the commit graph graphics look very nice, but the vertical ruler looks ugly as it is still painted with ISO-8859-1 graphics. It looks like
    
    ```
    ●─╮ Merge branch 'foo'  ┬commit 29e1d57a71515ee69730e5a9d81caaf5d667165e
    ● │ f                    Refs: [master]
    │ ● e                    Merge: 49d16e6 393894b
    ● │ d                    Author:     Björn Kautler <foo>
    ● │ c                    AuthorDate: Tue Sep 20 13:31:05 2016 +0200
    │ ● b                    Commit:     Björn Kautler <foo>
    ◎─╯ a                    CommitDate: Tue Sep 20 13:31:05 2016 +0200
    
                         Merge branch 'foo'
    
                      b | 0
                      e | 0
                      2 files changed, 0 insertions(+), 0 deletions(-)
    
    
                                   ┬│
                                    ┬│
                                     ┬│
                                      ┬│
                                       ┬│
                                        ┬│
    ```
  - Having `default`, the commit graph graphics _and_ the vertical ruler look ugly as they are painted with ISO-8859-1 graphics. It looks like
    
    ```
    M├ä┬┐ Merge branch 'foo'   ┬│commit 29e1d57a71515ee69730e5a9d81caaf5d667165e
    o ┬│┬│ f                   ┬│Refs: [master]
    │ oo e                    ┬│Merge: 49d16e6 393894b
    ┬││ d                    ┬│Author:     Björn Kautler <foo>
    ┬│ c                     ┬│AuthorDate: Tue Sep 20 13:31:05 2016 +0200
    │ o b                     ┬│Commit:     Björn Kautler <foo>
    -├ä├Öa                    ┬│CommitDate: Tue Sep 20 13:31:05 2016 +0200
                         ┬│
                          ┬│    Merge branch 'foo'
                         ┬│
                          ┬│ b | 0
                         ┬│ e | 0
                         ┬│ 2 files changed, 0 insertions(+), 0 deletions(-)
                         ┬│
                          ┬│
                           ┬│
    ```
    
    It would be nice if `utf-8` would be the default if started with UTF-8 and at most have a setting to switch to ISO-8859-1.
  - Also, using `default` does not repaint the screen properly.
    - If you switch from ugly `default`
      
      ```
      M├ä┬┐erge branch 'foo'
      o ┬│f
      ┬│ oe
      o ┬│d
      o ┬│c
      ┬│ ob
      I-├ä├Ö
      ```
      
      to nice (if no vertical ruler is shown) `utf-8`, then there remain characters where they don't belong
      
      ```
      ●─╮┬┐erge branch 'foo'
      ● ││f
      │ ●oe
      ● ││d
      ● ││c
      │ ●ob
      ◎─╯ä├Ö
      ```
      
      until lines are repainted by switching view or selecting lines one after the other
    - Even if you only switch views while in `default` it keeps artifact characters.
      
      Main view
      
      ```
      M├ä┬┐erge branch 'foo'
      o ┬│f
      ┬│ oe
      o ┬│d
      o ┬│c
      ┬│ ob
      I-├ä├Ö
      ```
      
      Pressing `d`
      
      ```
      commit 29e1d57a71515ee69730e5a9d81caaf5d667165e
      Refs: [master]
      Merge: 49d16e6 393894b
      Author:     Björn Kautler <foo>
      AuthorDate: Tue Sep 20 13:31:05 2016 +0200
      Commit:     Björn Kautler <foo>
      CommitDate: Tue Sep 20 13:31:05 2016 +0200
      
      Merge branch 'foo'
      
      b | 0
      e | 0
      2 files changed, 0 insertions(+), 0 deletions(-)
      ```
      
      Pressing `m`
      
      ```
      M├ä┬┐ Merge branch 'foo'
      o ┬│ f
      ┬│ o e
      o ┬│ d
      o ┬│ c
      ┬│ o b
      I├ä├Ö a
      
      Mer
      
      b | 0
      e | 0
      2 file
      ```

**Comment by Vampire** [comment]
The vertical ruler that separates the line numbers from the remaining line suffers from the same issues than the split view vertical ruler.

**Comment by jonas** [comment]
Thanks for the very detailed bug report. I fixed what I believe is the main issue, namely repainting the display when toggling `line-graphics`. I didn't find an easy way to skip the UTF-8 option if the terminal/environment does not support it. While this would be nice to have, I think it is mainly an inconvenience when trying out the options.

**Comment by xzxzzxzxzca** [comment]
I'm having a similar issue when I have `LANG=en_DE.UTF-8` exported. Changing to `en_US` fixes it, but `DE` is what my desktop environment sets (and which is correct). Graphical symbols look scrambled like  so:
```
~W~O ~T~@ ~T~B ~T~@ ~U
```

**Comment by Vampire** [comment]
@jonas I tested tig again now with 2.4.1 and as far as I can tell, nothing at all changed.
All things I reported are still happening like described. :-(

**Comment by technikhil314** [comment]
I am facing same issue. Any fixes or any duplicate of this?
tig version 2.5.1
ncursesw version 6.2.20200212

![Screenshot from 2020-10-13 20-08-33](https://user-images.githubusercontent.com/6815560/95875708-f06b9980-0d8f-11eb-8054-f6f6b6d183da.png)

**Comment by kdheepak** [comment]
I'm also still experiencing this. Is there a fix for this?
